apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: a85855fmq-dotnet-basic-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/a85855fmq-dotnet-basic